project: 
  type: website
  
website: 
  title: "Kansas Economic Data"
  navbar: 
    background: dark
    search: true
    right: 
      - text: "Home"
        file: Quartopage.qmd
      - text: "About"
        file: about.qmd
output:
  quarto::html_document:
    embed_resources: true
    page_layout: full
    css: styles.css
    toc: true
    includes:
      after_body: footer.html

format: 
  html:
    embed-resources: true
    page-layout: full
    css: styles.css
    toc: true