project: 
  type: website
  
website: 
  title: "Kansas Economic Data"
  page-footer:
    background: dark
    left: 
      - text: "GitHub Repo"
        url: "https://github.com/yourusername/yourrepository"
    center:
      - text: "&trade;"

  navbar: 
    background: dark
    search: true
    right: 
      - text: "Home"
        file: Quartopage.qmd
      - text: "About"
        file: about.qmd
  

format: 
  html:
    embed-resources: true
    page-layout: full
    toc: false
    css: styles.css
    footer: footer.html